/*This code is automatically generated by the tool, please do not manually modify it.*/
namespace GameMain.Hotfix
{
	public static partial class Constant
	{
		public enum EEntityGroupName
		{
			/// <summary>
			/// 默认
			/// </summary>
			Default,
		}
		public enum ESoundGroupName
		{
			/// <summary>
			/// 背景音乐
			/// </summary>
			Music,
			/// <summary>
			/// 音效
			/// </summary>
			Sound,
		}
		public enum EUIGroupName
		{
			Default,
			/// <summary>
			/// 一直处于底部的界面
			/// </summary>
			AlwaysBottomUI,
			/// <summary>
			/// 背景界面
			/// </summary>
			BackgroundUI,
			/// <summary>
			/// 公共界面
			/// </summary>
			CommonUI,
			/// <summary>
			/// 动画界面
			/// </summary>
			AnimationOnUI,
			/// <summary>
			/// 弹出界面
			/// </summary>
			PopupUI,
			/// <summary>
			/// 引导界面
			/// </summary>
			GuideUI,
		}
	}
}
