/************************************************************
 This file is automatically generated by the tool, please do not modify it directly。
 *************************************************************/

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityGameFramework.Runtime;

namespace GameMain.Hotfix
{
    /// <summary>
    /// EntityGroup
    /// </summary>
    public class DTEntityGroupTable : DataRowBase
    {
        private int mId = 0;

        /// <summary>
        /// 
        /// </summary>
        public override int Id => mId;

        /// <summary>
        /// 实体组名称
        /// </summary>
        public string Name {get; private set;}

        /// <summary>
        /// 实体组实例对象池自动释放可释放对象的间隔秒数
        /// </summary>
        public float InstanceAutoReleaseInterval {get; private set;}

        /// <summary>
        /// 实体组实例对象池的容量
        /// </summary>
        public int InstanceCapacity {get; private set;}

        /// <summary>
        /// 实体组实例对象池对象过期秒数
        /// </summary>
        public float InstanceExpireTime {get; private set;}

        /// <summary>
        /// 实体组实例对象池的优先级
        /// </summary>
        public int InstancePriority {get; private set;}


        public override bool ParseDataRow(string dataRowString, object userData)
        {
            var columnStrings = dataRowString.Split(DataTableExtension.DataSplitSeparators);
            for (var i = 0; i < columnStrings.Length; i++)
            {
                columnStrings[i] = columnStrings[i].Trim(DataTableExtension.DataTrimSeparators);
            }

            var index = 0;
            index++;
            mId = int.Parse(columnStrings[index++]);
            index++;
            Name = columnStrings[index++];
            InstanceAutoReleaseInterval = float.Parse(columnStrings[index++]);
            InstanceCapacity = int.Parse(columnStrings[index++]);
            InstanceExpireTime = float.Parse(columnStrings[index++]);
            InstancePriority = int.Parse(columnStrings[index++]);

            GeneratePropertyArray();
            return true;
        }

        public override bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
        {
            using (var memoryStream = new MemoryStream(dataRowBytes, startIndex, length, false))
            {
                using (var binaryReader = new BinaryReader(memoryStream, Encoding.UTF8))
                {
                    mId = binaryReader.Read7BitEncodedInt32();
                    Name = binaryReader.ReadString();
                    InstanceAutoReleaseInterval = binaryReader.ReadSingle();
                    InstanceCapacity = binaryReader.Read7BitEncodedInt32();
                    InstanceExpireTime = binaryReader.ReadSingle();
                    InstancePriority = binaryReader.Read7BitEncodedInt32();
                }
            }

            GeneratePropertyArray();
            return true;
        }


        private void GeneratePropertyArray()
        {
        }
    }
}