/************************************************************
 This file is automatically generated by the tool, please do not modify it directly。
 *************************************************************/

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityGameFramework.Runtime;

namespace GameMain.Hotfix
{
    /// <summary>
    /// SoundGroupTable
    /// </summary>
    public class DTSoundGroupTable : DataRowBase
    {
        private int mId = 0;

        /// <summary>
        /// 
        /// </summary>
        public override int Id => mId;

        /// <summary>
        /// 声音组名称
        /// </summary>
        public string Name {get; private set;}

        /// <summary>
        /// 获取声音代理数
        /// </summary>
        public int SoundAgentCount {get; private set;}

        /// <summary>
        /// 声音组中的声音是否避免被同优先级声音替换
        /// </summary>
        public bool AvoidBeingReplacedBySamePriority {get; private set;}

        /// <summary>
        /// 声音组静音
        /// </summary>
        public bool Mute {get; private set;}

        /// <summary>
        /// 声音组音量
        /// </summary>
        public float Volume {get; private set;}


        public override bool ParseDataRow(string dataRowString, object userData)
        {
            var columnStrings = dataRowString.Split(DataTableExtension.DataSplitSeparators);
            for (var i = 0; i < columnStrings.Length; i++)
            {
                columnStrings[i] = columnStrings[i].Trim(DataTableExtension.DataTrimSeparators);
            }

            var index = 0;
            index++;
            mId = int.Parse(columnStrings[index++]);
            index++;
            Name = columnStrings[index++];
            SoundAgentCount = int.Parse(columnStrings[index++]);
            AvoidBeingReplacedBySamePriority = bool.Parse(columnStrings[index++]);
            Mute = bool.Parse(columnStrings[index++]);
            Volume = float.Parse(columnStrings[index++]);

            GeneratePropertyArray();
            return true;
        }

        public override bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
        {
            using (var memoryStream = new MemoryStream(dataRowBytes, startIndex, length, false))
            {
                using (var binaryReader = new BinaryReader(memoryStream, Encoding.UTF8))
                {
                    mId = binaryReader.Read7BitEncodedInt32();
                    Name = binaryReader.ReadString();
                    SoundAgentCount = binaryReader.Read7BitEncodedInt32();
                    AvoidBeingReplacedBySamePriority = binaryReader.ReadBoolean();
                    Mute = binaryReader.ReadBoolean();
                    Volume = binaryReader.ReadSingle();
                }
            }

            GeneratePropertyArray();
            return true;
        }


        private void GeneratePropertyArray()
        {
        }
    }
}