/************************************************************
 This file is automatically generated by the tool, please do not modify it directly。
 *************************************************************/

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityGameFramework.Runtime;

namespace GameMain.Hotfix
{
    /// <summary>
    /// ServerTable
    /// </summary>
    public class DTServerTable : DataRowBase
    {
        private int mId = 0;

        /// <summary>
        /// 
        /// </summary>
        public override int Id => mId;

        /// <summary>
        /// 通道名称
        /// </summary>
        public string ChannelName {get; private set;}

        /// <summary>
        /// 服务器名称
        /// </summary>
        public string ServerName {get; private set;}

        /// <summary>
        /// IP地址
        /// </summary>
        public string IP {get; private set;}

        /// <summary>
        /// 端口
        /// </summary>
        public string Port {get; private set;}


        public override bool ParseDataRow(string dataRowString, object userData)
        {
            var columnStrings = dataRowString.Split(DataTableExtension.DataSplitSeparators);
            for (var i = 0; i < columnStrings.Length; i++)
            {
                columnStrings[i] = columnStrings[i].Trim(DataTableExtension.DataTrimSeparators);
            }

            var index = 0;
            index++;
            mId = int.Parse(columnStrings[index++]);
            index++;
            ChannelName = columnStrings[index++];
            ServerName = columnStrings[index++];
            IP = columnStrings[index++];
            Port = columnStrings[index++];

            GeneratePropertyArray();
            return true;
        }

        public override bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
        {
            using (var memoryStream = new MemoryStream(dataRowBytes, startIndex, length, false))
            {
                using (var binaryReader = new BinaryReader(memoryStream, Encoding.UTF8))
                {
                    mId = binaryReader.Read7BitEncodedInt32();
                    ChannelName = binaryReader.ReadString();
                    ServerName = binaryReader.ReadString();
                    IP = binaryReader.ReadString();
                    Port = binaryReader.ReadString();
                }
            }

            GeneratePropertyArray();
            return true;
        }


        private void GeneratePropertyArray()
        {
        }
    }
}