/************************************************************
 This file is automatically generated by the tool, please do not modify it directly。
 *************************************************************/

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityGameFramework.Runtime;

namespace GameMain.Hotfix
{
    /// <summary>
    /// UITable
    /// </summary>
    public class DTUITable : DataRowBase
    {
        private int mId = 0;

        /// <summary>
        /// 
        /// </summary>
        public override int Id => mId;

        /// <summary>
        /// 界面资源名称
        /// </summary>
        public string AssetName {get; private set;}

        /// <summary>
        /// 界面组名称
        /// </summary>
        public string GroupName {get; private set;}

        /// <summary>
        /// 加载界面资源的优先级
        /// </summary>
        public int Priority {get; private set;}

        /// <summary>
        /// 是否暂停被覆盖的界面
        /// </summary>
        public bool PauseCovered {get; private set;}


        public override bool ParseDataRow(string dataRowString, object userData)
        {
            var columnStrings = dataRowString.Split(DataTableExtension.DataSplitSeparators);
            for (var i = 0; i < columnStrings.Length; i++)
            {
                columnStrings[i] = columnStrings[i].Trim(DataTableExtension.DataTrimSeparators);
            }

            var index = 0;
            index++;
            mId = int.Parse(columnStrings[index++]);
            index++;
            AssetName = columnStrings[index++];
            GroupName = columnStrings[index++];
            Priority = int.Parse(columnStrings[index++]);
            PauseCovered = bool.Parse(columnStrings[index++]);

            GeneratePropertyArray();
            return true;
        }

        public override bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
        {
            using (var memoryStream = new MemoryStream(dataRowBytes, startIndex, length, false))
            {
                using (var binaryReader = new BinaryReader(memoryStream, Encoding.UTF8))
                {
                    mId = binaryReader.Read7BitEncodedInt32();
                    AssetName = binaryReader.ReadString();
                    GroupName = binaryReader.ReadString();
                    Priority = binaryReader.Read7BitEncodedInt32();
                    PauseCovered = binaryReader.ReadBoolean();
                }
            }

            GeneratePropertyArray();
            return true;
        }


        private void GeneratePropertyArray()
        {
        }
    }
}